package main

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/signal"
	"path/filepath"
	"strings"
	"syscall"
)

func main() {
	logger := log.New(os.Stdout, "relay-agent ", log.LstdFlags|log.Lmicroseconds)

	if len(os.Args) < 2 {
		usage()
		os.Exit(2)
	}

	switch os.Args[1] {
	case "pair":
		if err := runPair(os.Args[2:], logger); err != nil {
			logger.Fatalf("pair: %v", err)
		}
	case "run":
		if err := runAgent(os.Args[2:], logger); err != nil {
			logger.Fatalf("run: %v", err)
		}
	default:
		usage()
		os.Exit(2)
	}
}

func runPair(args []string, logger *log.Logger) error {
	configPath, err := defaultConfigPath()
	if err != nil {
		return err
	}

	hostName, _ := os.Hostname()

	flags := flag.NewFlagSet("pair", flag.ContinueOnError)
	serverURL := flags.String("server", "", "Relay server URL, for example https://192.168.1.10:8443")
	pairCode := flags.String("code", "", "Pairing code generated by the Relay app")
	deviceName := flags.String("name", hostName, "Display name for this Mac")
	platform := flags.String("platform", "macOS", "Platform label to report to Relay")
	path := flags.String("config", configPath, "Config file path")
	allowInsecureTLS := flags.Bool("allow-insecure-tls", false, "Skip TLS verification for self-signed development certificates")
	if err := flags.Parse(args); err != nil {
		return err
	}

	if strings.TrimSpace(*serverURL) == "" {
		return errors.New("--server is required")
	}
	if strings.TrimSpace(*pairCode) == "" {
		return errors.New("--code is required")
	}

	body, err := json.Marshal(agentPairRequest{
		Code:       strings.TrimSpace(*pairCode),
		DeviceName: strings.TrimSpace(*deviceName),
		Platform:   strings.TrimSpace(*platform),
	})
	if err != nil {
		return fmt.Errorf("encode pair request: %w", err)
	}

	request, err := http.NewRequest(http.MethodPost, strings.TrimRight(*serverURL, "/")+"/v1/agent/pair", bytes.NewReader(body))
	if err != nil {
		return fmt.Errorf("build pair request: %w", err)
	}
	request.Header.Set("Content-Type", "application/json")
	request.Header.Set("Accept", "application/json")

	response, err := httpClient(*allowInsecureTLS).Do(request)
	if err != nil {
		return fmt.Errorf("send pair request: %w", err)
	}
	defer response.Body.Close()

	if response.StatusCode != http.StatusCreated {
		var serverError struct {
			Error string `json:"error"`
		}
		_ = json.NewDecoder(response.Body).Decode(&serverError)
		if serverError.Error == "" {
			serverError.Error = response.Status
		}
		return errors.New(serverError.Error)
	}

	var pairResponse AgentPairResponse
	if err := json.NewDecoder(response.Body).Decode(&pairResponse); err != nil {
		return fmt.Errorf("decode pair response: %w", err)
	}

	cfg := AgentConfig{
		ServerURL:        pairResponse.ServerURL,
		AgentID:          pairResponse.AgentID,
		AgentToken:       pairResponse.AgentToken,
		DeviceName:       strings.TrimSpace(*deviceName),
		Platform:         strings.TrimSpace(*platform),
		AllowInsecureTLS: *allowInsecureTLS,
	}

	if err := saveConfig(*path, cfg); err != nil {
		return err
	}

	logger.Printf("paired %s and saved config to %s", cfg.DeviceName, *path)
	return nil
}

func runAgent(args []string, logger *log.Logger) error {
	configPath, err := defaultConfigPath()
	if err != nil {
		return err
	}

	flags := flag.NewFlagSet("run", flag.ContinueOnError)
	path := flags.String("config", configPath, "Config file path")
	if err := flags.Parse(args); err != nil {
		return err
	}

	cfg, err := loadConfig(*path)
	if err != nil {
		return err
	}

	logger.Printf("starting relay agent for %s using %s", cfg.DeviceName, filepath.Clean(*path))

	ctx, cancel := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer cancel()

	return NewRunner(cfg, logger).Run(ctx)
}

func usage() {
	fmt.Fprintf(os.Stderr, "Usage:\n")
	fmt.Fprintf(os.Stderr, "  relay-agent pair --server https://HOST:8443 --code ABC12345 [--allow-insecure-tls]\n")
	fmt.Fprintf(os.Stderr, "  relay-agent run [--config ~/.relay-agent/config.json]\n")
}
